Add TLS support (#66)
carbynestack/carbynestack pull request #107
Opened 2024-08-21 09:35 UTC by benjaminhettwer

2024-09-17 08:12 UTC, sbckr requested changes
please update copyright headers and add yourself to the `NOTICE.md` file

2024-09-17 08:12 UTC, sbckr commented on deployments/helmfile.d/0030.istio.yaml
please update copyright header

2024-09-17 08:12 UTC, sbckr commented on deployments/helmfile.d/0300.ephemeral.yaml
please update copyright header

2025-03-10 13:59 UTC, sbckr commented on deployments/charts/istio/templates/request-authentication.yaml
> +            paths: ["/protobuf.Discovery*"]
remove

2025-03-10 14:00 UTC, sbckr commented on deployments/charts/istio/templates/request-authentication.yaml
> +        # Allow all MPC party interactions. AuthN and AuthZ is handled via mtls established by ephemeral and its mpc
remove "and its mpc frameworks"

2025-03-13 13:50 UTC, strieflin submitted a review, later dismissed
LGTM

2025-03-18 14:09 UTC, sbckr approved these changes
LGTM

2025-03-18 14:10 UTC, merged