Use official Minio Chart instead of custom one
carbynestack/carbynestack pull request #32
Opened 2022-03-14 16:23 UTC by grafjo

the helmfile.d/0020.minio.yaml mentioned that the minio deployment is
based on the minio operator ... but that's not true. It's a self written
helm chart without using the CRDs of the minio operator!

Our motivation was to replace the custom helm deployment with the
upstream one from minio. So we can enable persistence, without adding
that as a feature to the self written helm chart.

Co-authored-by: Petra Scherer <scherer@synyx.de>
Co-authored-by: Timo Klenk <klenk@synyx.de>
Signed-off-by: Johannes Graf <graf@synyx.de>

2022-04-07 08:12 UTC, strieflin commented
@grafjo: Any updates here. Did you have time to think about my remarks?

2022-04-07 11:59 UTC, strieflin requested changes

2022-05-09 09:49 UTC, grafjo commented on helmfile.d/0020.minio.yaml
> +          size: 10Gi
I have adjusted memory and storage as recommended

2022-05-09 12:11 UTC, strieflin approved these changes
LGTM

2022-05-09 12:12 UTC, merged